name: Projeto
version: ${version}
main: org.caique.mcgames.Projeto
api-version: 1.20
commands:
  login:
    description: Faz login no servidor
    usage: /<command> <senha>
  register:
    description: Registra uma conta no servidor
    usage: /<command> <senha> <confirmação>